### ISSUE TITLE
FastLED-master

### ISSUE THREAD

**Issue by rootTheLure** [AlexGyver/WS2812_FX#1]
Лучше переименовать FastLED-master в FastLED. "-master" название бранча с кодом, которое добавляется в название архива, когда скачиваешь как zip.

**Comment by AlexGyver** [comment]
немного не понял, разъяснишь? Я с гитхабом не работал особо

**Comment by rootTheLure** [comment]
Всё предельно просто! В git есть понятие бранч (branch, ветка) в которых могу быть разные версии кода например. Дефлотовый бранч в каждом репозитории это master:
![image](https://user-images.githubusercontent.com/5189654/29212695-93a027e4-7ea8-11e7-8e83-da3b8ca1de03.png)
Если скачивать любо репозиторий через терминал гита
`git clone <name>` 
то скачается папка с точным названием репозитория (библиотеки) например FastLED. Если скачивать через интерфейс гитхаба, то к названию автоматом добавляется название ветки из которой ты качаешь код
![image](https://user-images.githubusercontent.com/5189654/29212768-f1c93af4-7ea8-11e7-8b34-ddf676966bdd.png)
![image](https://user-images.githubusercontent.com/5189654/29212828-2189f526-7ea9-11e7-829c-02f27850b869.png)
В твоём случае библеотека назвыается просто FastLED, а не FastLED-master.

**Comment by AlexGyver** [comment]
то есть чисто косметическая штука? Чтобы не был слова мастер?

**Comment by rootTheLure** [comment]
По сути да, оч глаз режет...

**Comment by AlexGyver** [comment]
окей, принято =)

**Comment by Nazarufc** [comment]
Alex помоги пж, не могу понять в чем дело, тестовую прошивку грузит, а твой скетчь не могу загрузить, пишет такую ошибку:     (что я делаю не так?(((()
Arduino: 1.8.7 (Windows 7), Плата:"Arduino Nano, ATmega328P (Old Bootloader)"

java.io.IOException: Отказано в доступе
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at processing.app.BaseNoGui.saveFile(BaseNoGui.java:885)
	at processing.app.SketchFile.save(SketchFile.java:287)
	at processing.app.Sketch.save(Sketch.java:138)
	at processing.app.SketchController.save(SketchController.java:352)
	at processing.app.Editor.handleSave2(Editor.java:1883)
	at processing.app.Editor.handleSave(Editor.java:1858)
	at processing.app.Editor.handleExport(Editor.java:2000)
	at processing.app.EditorToolbar.mousePressed(EditorToolbar.java:378)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4531)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Отказано в доступе
In file included from C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\WS2812_FX_rndChange_light.ino:8:0:

C:\Program Files (x86)\Arduino\libraries\FastLED/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.005

 #    pragma message "FastLED version 3.001.005"

                     ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\WS2812_FX_rndChange_light.ino: In function 'void setup()':

WS2812_FX_rndChange_light:204:24: error: 'one_color_all' was not declared in this scope

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\WS2812_FX_rndChange_light.ino: In function 'void loop()':

WS2812_FX_rndChange_light:222:24: error: 'change_mode' was not declared in this scope

WS2812_FX_rndChange_light:233:27: error: 'rainbow_fade' was not declared in this scope

WS2812_FX_rndChange_light:234:27: error: 'rainbow_loop' was not declared in this scope

WS2812_FX_rndChange_light:235:27: error: 'random_burst' was not declared in this scope

WS2812_FX_rndChange_light:236:27: error: 'color_bounce' was not declared in this scope

WS2812_FX_rndChange_light:237:31: error: 'color_bounceFADE' was not declared in this scope

WS2812_FX_rndChange_light:238:28: error: 'ems_lightsONE' was not declared in this scope

WS2812_FX_rndChange_light:239:28: error: 'ems_lightsALL' was not declared in this scope

WS2812_FX_rndChange_light:240:22: error: 'flicker' was not declared in this scope

WS2812_FX_rndChange_light:241:34: error: 'pulse_one_color_all' was not declared in this scope

WS2812_FX_rndChange_light:242:38: error: 'pulse_one_color_all_rev' was not declared in this scope

WS2812_FX_rndChange_light:243:28: error: 'fade_vertical' was not declared in this scope

WS2812_FX_rndChange_light:244:21: error: 'rule30' was not declared in this scope

WS2812_FX_rndChange_light:245:27: error: 'random_march' was not declared in this scope

WS2812_FX_rndChange_light:246:24: error: 'rwb_march' was not declared in this scope

WS2812_FX_rndChange_light:247:24: error: 'radiation' was not declared in this scope

WS2812_FX_rndChange_light:248:34: error: 'color_loop_vardelay' was not declared in this scope

WS2812_FX_rndChange_light:249:26: error: 'white_temps' was not declared in this scope

WS2812_FX_rndChange_light:250:30: error: 'sin_bright_wave' was not declared in this scope

WS2812_FX_rndChange_light:251:29: error: 'pop_horizontal' was not declared in this scope

WS2812_FX_rndChange_light:252:32: error: 'quad_bright_curve' was not declared in this scope

WS2812_FX_rndChange_light:253:20: error: 'flame' was not declared in this scope

WS2812_FX_rndChange_light:254:31: error: 'rainbow_vertical' was not declared in this scope

WS2812_FX_rndChange_light:255:21: error: 'pacman' was not declared in this scope

WS2812_FX_rndChange_light:256:31: error: 'random_color_pop' was not declared in this scope

WS2812_FX_rndChange_light:257:31: error: 'ems_lightsSTROBE' was not declared in this scope

WS2812_FX_rndChange_light:258:28: error: 'rgb_propeller' was not declared in this scope

WS2812_FX_rndChange_light:259:19: error: 'kitt' was not declared in this scope

WS2812_FX_rndChange_light:260:21: error: 'matrix' was not declared in this scope

WS2812_FX_rndChange_light:261:31: error: 'new_rainbow_loop' was not declared in this scope

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\WS2812_FX_rndChange_light.ino: In function 'void change_mode(int)':

WS2812_FX_rndChange_light:268:34: error: 'one_color_all' was not declared in this scope

WS2812_FX_rndChange_light:278:24: error: 'one_color_all' was not declared in this scope

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void color_bounceFADE()':

LED_EFFECT_FUNCTIONS:88:29: error: 'adjacent_cw' was not declared in this scope

   int iL1 = adjacent_cw(idex);

                             ^

LED_EFFECT_FUNCTIONS:91:30: error: 'adjacent_ccw' was not declared in this scope

   int iR1 = adjacent_ccw(idex);

                              ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void ems_lightsONE()':

LED_EFFECT_FUNCTIONS:130:36: error: 'antipodal_index' was not declared in this scope

   int idexB = antipodal_index(idexR);

                                    ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void ems_lightsALL()':

LED_EFFECT_FUNCTIONS:153:36: error: 'antipodal_index' was not declared in this scope

   int idexB = antipodal_index(idexR);

                                    ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void fade_vertical()':

LED_EFFECT_FUNCTIONS:220:37: error: 'horizontal_index' was not declared in this scope

   int idexB = horizontal_index(idexA);

                                     ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void rule30()':

LED_EFFECT_FUNCTIONS:251:18: error: 'copy_led_array' was not declared in this scope

   copy_led_array();

                  ^

LED_EFFECT_FUNCTIONS:256:24: error: 'adjacent_cw' was not declared in this scope

     iCW = adjacent_cw(i);

                        ^

LED_EFFECT_FUNCTIONS:257:26: error: 'adjacent_ccw' was not declared in this scope

     iCCW = adjacent_ccw(i);

                          ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void random_march()':

LED_EFFECT_FUNCTIONS:288:18: error: 'copy_led_array' was not declared in this scope

   copy_led_array();

                  ^

LED_EFFECT_FUNCTIONS:292:29: error: 'adjacent_ccw' was not declared in this scope

     iCCW = adjacent_ccw(idex);

                             ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void rwb_march()':

LED_EFFECT_FUNCTIONS:302:18: error: 'copy_led_array' was not declared in this scope

   copy_led_array();

                  ^

LED_EFFECT_FUNCTIONS:326:26: error: 'adjacent_ccw' was not declared in this scope

     iCCW = adjacent_ccw(i);

                          ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void pop_horizontal()':

LED_EFFECT_FUNCTIONS:449:31: error: 'horizontal_index' was not declared in this scope

     ix = horizontal_index(idex);

                               ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void flame()':

LED_EFFECT_FUNCTIONS:496:32: error: 'horizontal_index' was not declared in this scope

     int ih = horizontal_index(i);

                                ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void rainbow_vertical()':

LED_EFFECT_FUNCTIONS:514:37: error: 'horizontal_index' was not declared in this scope

   int idexB = horizontal_index(idexA);

                                     ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void pacman()':

LED_EFFECT_FUNCTIONS:529:35: error: 'set_color_led' was not declared in this scope

       set_color_led(i, 255, 255, 0);

                                   ^

LED_EFFECT_FUNCTIONS:534:35: error: 'set_color_led' was not declared in this scope

       set_color_led(i, 255, 255, 0);

                                   ^

LED_EFFECT_FUNCTIONS:540:35: error: 'set_color_led' was not declared in this scope

       set_color_led(i, 255, 255, 0);

                                   ^

LED_EFFECT_FUNCTIONS:548:35: error: 'set_color_led' was not declared in this scope

       set_color_led(i, 255, 255, 0);

                                   ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void matrix()':

LED_EFFECT_FUNCTIONS:633:18: error: 'copy_led_array' was not declared in this scope

   copy_led_array();

                  ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void strip_march_cw()':

LED_EFFECT_FUNCTIONS:644:18: error: 'copy_led_array' was not declared in this scope

   copy_led_array();

                  ^

LED_EFFECT_FUNCTIONS:647:24: error: 'adjacent_cw' was not declared in this scope

     iCW = adjacent_cw(i);

                        ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void strip_march_ccw()':

LED_EFFECT_FUNCTIONS:657:18: error: 'copy_led_array' was not declared in this scope

   copy_led_array();

                  ^

LED_EFFECT_FUNCTIONS:660:26: error: 'adjacent_ccw' was not declared in this scope

     iCCW = adjacent_ccw(i);

                          ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void demo_modeA()':

LED_EFFECT_FUNCTIONS:773:14: error: 'demo_modeB' was not declared in this scope

   demo_modeB();

              ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void colorWipe(byte, byte, byte, int)':

LED_EFFECT_FUNCTIONS:816:33: error: 'setPixel' was not declared in this scope

     setPixel(i, red, green, blue);

                                 ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void CylonBounce(byte, byte, byte, int, int, int)':

LED_EFFECT_FUNCTIONS:825:19: error: 'setAll' was not declared in this scope

     setAll(0, 0, 0);

                   ^

LED_EFFECT_FUNCTIONS:826:48: error: 'setPixel' was not declared in this scope

     setPixel(i, red / 10, green / 10, blue / 10);

                                                ^

LED_EFFECT_FUNCTIONS:838:19: error: 'setAll' was not declared in this scope

     setAll(0, 0, 0);

                   ^

LED_EFFECT_FUNCTIONS:839:48: error: 'setPixel' was not declared in this scope

     setPixel(i, red / 10, green / 10, blue / 10);

                                                ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void Fire(int, int, int)':

LED_EFFECT_FUNCTIONS:881:34: error: 'setPixelHeatColor' was not declared in this scope

     setPixelHeatColor(j, heat[j] );

                                  ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void setPixelHeatColor(int, byte)':

LED_EFFECT_FUNCTIONS:898:39: error: 'setPixel' was not declared in this scope

     setPixel(Pixel, 255, 255, heatramp);

                                       ^

LED_EFFECT_FUNCTIONS:900:37: error: 'setPixel' was not declared in this scope

     setPixel(Pixel, 255, heatramp, 0);

                                     ^

LED_EFFECT_FUNCTIONS:902:35: error: 'setPixel' was not declared in this scope

     setPixel(Pixel, heatramp, 0, 0);

                                   ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void NewKITT(byte, byte, byte, int, int, int)':

LED_EFFECT_FUNCTIONS:908:65: error: 'RightToLeft' was not declared in this scope

   RightToLeft(red, green, blue, EyeSize, SpeedDelay, ReturnDelay);

                                                                 ^

LED_EFFECT_FUNCTIONS:909:65: error: 'LeftToRight' was not declared in this scope

   LeftToRight(red, green, blue, EyeSize, SpeedDelay, ReturnDelay);

                                                                 ^

LED_EFFECT_FUNCTIONS:910:69: error: 'OutsideToCenter' was not declared in this scope

   OutsideToCenter(red, green, blue, EyeSize, SpeedDelay, ReturnDelay);

                                                                     ^

LED_EFFECT_FUNCTIONS:911:69: error: 'CenterToOutside' was not declared in this scope

   CenterToOutside(red, green, blue, EyeSize, SpeedDelay, ReturnDelay);

                                                                     ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void CenterToOutside(byte, byte, byte, int, int, int)':

LED_EFFECT_FUNCTIONS:920:19: error: 'setAll' was not declared in this scope

     setAll(0, 0, 0);

                   ^

LED_EFFECT_FUNCTIONS:922:48: error: 'setPixel' was not declared in this scope

     setPixel(i, red / 10, green / 10, blue / 10);

                                                ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void OutsideToCenter(byte, byte, byte, int, int, int)':

LED_EFFECT_FUNCTIONS:942:19: error: 'setAll' was not declared in this scope

     setAll(0, 0, 0);

                   ^

LED_EFFECT_FUNCTIONS:944:48: error: 'setPixel' was not declared in this scope

     setPixel(i, red / 10, green / 10, blue / 10);

                                                ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void LeftToRight(byte, byte, byte, int, int, int)':

LED_EFFECT_FUNCTIONS:964:19: error: 'setAll' was not declared in this scope

     setAll(0, 0, 0);

                   ^

LED_EFFECT_FUNCTIONS:965:48: error: 'setPixel' was not declared in this scope

     setPixel(i, red / 10, green / 10, blue / 10);

                                                ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void RightToLeft(byte, byte, byte, int, int, int)':

LED_EFFECT_FUNCTIONS:978:19: error: 'setAll' was not declared in this scope

     setAll(0, 0, 0);

                   ^

LED_EFFECT_FUNCTIONS:979:48: error: 'setPixel' was not declared in this scope

     setPixel(i, red / 10, green / 10, blue / 10);

                                                ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void rainbowCycle(int)':

LED_EFFECT_FUNCTIONS:997:50: error: 'Wheel' was not declared in this scope

       c = Wheel(((i * 256 / LED_COUNT) + j) & 255);

                                                  ^

LED_EFFECT_FUNCTIONS:998:41: error: 'setPixel' was not declared in this scope

       setPixel(i, *c, *(c + 1), *(c + 2));

                                         ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void TwinkleRandom(int, int, boolean)':

LED_EFFECT_FUNCTIONS:1029:17: error: 'setAll' was not declared in this scope

   setAll(0, 0, 0);

                 ^

LED_EFFECT_FUNCTIONS:1032:79: error: 'setPixel' was not declared in this scope

     setPixel(random(LED_COUNT), random(0, 255), random(0, 255), random(0, 255));

                                                                               ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void RunningLights(byte, byte, byte, int)':

LED_EFFECT_FUNCTIONS:1057:60: error: 'setPixel' was not declared in this scope

                ((sin(i + Position) * 127 + 128) / 255)*blue);

                                                            ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void Sparkle(byte, byte, byte, int)':

LED_EFFECT_FUNCTIONS:1068:35: error: 'setPixel' was not declared in this scope

   setPixel(Pixel, red, green, blue);

                                   ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void SnowSparkle(byte, byte, byte, int, int)':

LED_EFFECT_FUNCTIONS:1076:26: error: 'setAll' was not declared in this scope

   setAll(red, green, blue);

                          ^

LED_EFFECT_FUNCTIONS:1079:35: error: 'setPixel' was not declared in this scope

   setPixel(Pixel, 0xff, 0xff, 0xff);

                                   ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void theaterChase(byte, byte, byte, int)':

LED_EFFECT_FUNCTIONS:1092:41: error: 'setPixel' was not declared in this scope

         setPixel(i + q, red, green, blue);  //turn every third pixel on

                                         ^

LED_EFFECT_FUNCTIONS:1097:32: error: 'setPixel' was not declared in this scope

         setPixel(i + q, 0, 0, 0);    //turn every third pixel off

                                ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void theaterChaseRainbow(int)':

LED_EFFECT_FUNCTIONS:1111:47: error: 'setPixel' was not declared in this scope

         setPixel(i + q, *c, *(c + 1), *(c + 2)); //turn every third pixel on

                                               ^

LED_EFFECT_FUNCTIONS:1116:32: error: 'setPixel' was not declared in this scope

         setPixel(i + q, 0, 0, 0);    //turn every third pixel off

                                ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void Strobe(byte, byte, byte, int, int, int)':

LED_EFFECT_FUNCTIONS:1125:28: error: 'setAll' was not declared in this scope

     setAll(red, green, blue);

                            ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void BouncingBalls(byte, byte, byte, int)':

LED_EFFECT_FUNCTIONS:1176:45: error: 'setPixel' was not declared in this scope

       setPixel(Position[i], red, green, blue);

                                             ^

LED_EFFECT_FUNCTIONS:1179:19: error: 'setAll' was not declared in this scope

     setAll(0, 0, 0);

                   ^

C:\Users\nazar\AppData\Local\Temp\arduino_modified_sketch_398874\LED_EFFECT_FUNCTIONS.ino: In function 'void BouncingColoredBalls(int, byte (*)[3])':

LED_EFFECT_FUNCTIONS:1223:69: error: 'setPixel' was not declared in this scope

       setPixel(Position[i], colors[i][0], colors[i][1], colors[i][2]);

                                                                     ^

LED_EFFECT_FUNCTIONS:1226:19: error: 'setAll' was not declared in this scope

     setAll(0, 0, 0);

                   ^

exit status 1
'one_color_all' was not declared in this scope

Этот отчёт будет иметь больше информации с
включенной опцией Файл -> Настройки ->
"Показать подробный вывод во время компиляции"

**Comment by dukov1975** [comment]
java.io.IOException: Отказано в доступе - напимано же + библиотэка не подтянулась

**Comment by dukov1975** [comment]
И по кайфу такие портянки присылать?
